# Generated by Django 3.0.8 on 2021-04-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='path_photo',
            field=models.ImageField(upload_to='static/photo'),
        ),
    ]
