# Generated by Django 3.0.8 on 2021-04-14 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0002_auto_20210414_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал времени'},
        ),
        migrations.AddField(
            model_name='journal',
            name='path_on_video',
            field=models.ImageField(blank=True, upload_to='static/video'),
        ),
        migrations.AddField(
            model_name='journal',
            name='status_recoding_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='Работники',
        ),
    ]
