# Generated by Django 3.0.8 on 2021-04-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0003_auto_20210414_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал_времени'},
        ),
    ]
