# Generated by Django 3.0.8 on 2021-04-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_system', '0004_auto_20210414_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал времени'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Работники'},
        ),
        migrations.AlterField(
            model_name='journal',
            name='path_on_video',
            field=models.ImageField(blank=True, upload_to='static/video', verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status_recoding_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в журнал'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_system.User', verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='path_photo',
            field=models.ImageField(upload_to='static/photo', verbose_name='Загруженное фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterModelTable(
            name='journal',
            table='Журнал времени',
        ),
    ]
